-- Portable SQL: runs on PostgreSQL and on H2 in PostgreSQL mode.

create table users (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null,
    password_hash varchar(100) not null,
    display_name  varchar(100) not null,
    created_at    timestamp with time zone not null,
    constraint uk_users_email unique (email)
);

create table job_applications (
    id           bigint generated by default as identity primary key,
    owner_id     bigint       not null,
    company      varchar(120) not null,
    role         varchar(120) not null,
    location     varchar(120),
    url          varchar(500),
    salary_range varchar(80),
    status       varchar(20)  not null,
    applied_on   date,
    follow_up_on date,
    notes        varchar(4000),
    created_at   timestamp with time zone not null,
    updated_at   timestamp with time zone not null,
    constraint fk_job_applications_owner foreign key (owner_id) references users (id) on delete cascade
);

create index idx_job_applications_owner_status on job_applications (owner_id, status);
create index idx_job_applications_owner_follow_up on job_applications (owner_id, follow_up_on);

create table application_tags (
    application_id bigint      not null,
    tag            varchar(40) not null,
    constraint pk_application_tags primary key (application_id, tag),
    constraint fk_application_tags_application foreign key (application_id) references job_applications (id) on delete cascade
);

create table status_changes (
    id             bigint generated by default as identity primary key,
    application_id bigint      not null,
    from_status    varchar(20),
    to_status      varchar(20) not null,
    changed_at     timestamp with time zone not null,
    constraint fk_status_changes_application foreign key (application_id) references job_applications (id) on delete cascade
);

create index idx_status_changes_application on status_changes (application_id, changed_at);

create table interviews (
    id             bigint generated by default as identity primary key,
    application_id bigint       not null,
    scheduled_at   timestamp with time zone not null,
    type           varchar(20)  not null,
    notes          varchar(2000),
    created_at     timestamp with time zone not null,
    constraint fk_interviews_application foreign key (application_id) references job_applications (id) on delete cascade
);

create index idx_interviews_application on interviews (application_id, scheduled_at);
